name: aplikasi_targetku
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- State Management ---
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # --- Navigation ---
  go_router: ^13.0.0

  # --- Database ---
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # --- UI & Utilities (INI YANG KURANG TADI) ---
  google_fonts: ^6.1.0  # Untuk Font Poppins
  intl: ^0.19.0   
  image_picker: ^1.0.7      # Untuk Format Rupiah
  fpdart: ^1.1.0
  uuid: ^4.2.1
  logger: ^2.0.2

  # --- Data Class ---
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # --- Code Generation ---
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.3
  drift_dev: ^2.14.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png" # Siapkan gambar icon.png (1024x1024)
  min_sdk_android: 21

flutter_native_splash:
  color: "#6366F1" # Warna Indigo (Sesuai tema app)
  image: "assets/icon.png" # Logo di tengah
  branding: "assets/icon.png"
  color_dark: "#1E293B"
  fullscreen: true